---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Creating user1
      user:
        name: user1
        state: present
        create_home: true
        shell: /bin/bash

    - name: set up authorized keys for user1
      authorized_key:
        user: user1
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
